site_name: 2020_5BI_Team1

nav:
    - 'Project Model Canvas': 'project-canvas.pdf'
    - 'Business Model Canvas': 'business-model-canvas.pdf'
    - 'Project Charter 1': 'project_charter_client.md'
    - 'Project Charter 2': 'project_charter_server.md'
    - 'Software Requirements Specification': 'Software_Requirements_Specification.md'
    - 'Software Project Management Plan': 'Software_Project_Management_Plan.md'
    - 'Release Plan': 'Release_Plan.md'
    - 'Iteration Plan': 'Iteration_Plan.md'
    - 'Project Success Criteria client': 'Project_Success_Criteria_client.md'
    - 'Project Success Criteria server': 'Project_Success_Criteria_server.md'
    - 'Memo Of Understanding': 'Memo_of_understanding.md'

theme:
    name: readthedocs
