site_name: 2020_5BI_Team1

nav:
    - 'Project Model Canvas': 'project-canvas.pdf'
    - 'Business Model Canvas': 'business-model-canvas.pdf'
    - 'Project Charter client': 'project_charter_client.md'
    - 'Project Charter server': 'project_charter_server.md'
    - 'Software Requirements Specification': 'Software_Requirements_Specification.md'
    - 'Software Project Management Plan': 'Software_Project_Management_Plan.md'
    - 'Release Plan': 'Release_Plan.md'
    - 'Iteration Plan': 'Iteration_Plan.md'
    - 'Project Success Criteria client': 'Project_Success_Criteria_client.md'
    - 'Project Success Criteria server': 'Project_Success_Criteria_server.md'
    - 'Memo Of Understanding': 'Memo_of_understanding.md'
    - 'Test Plan': 'Test_Plan.md'
    - 'Test Case Specification': 'Test_case_specification.md'
    - 'User Guide client': 'User_Guide_Client.md'
    - 'User Guide server': 'User_Guide_Server.md'
    - 'Architecture, Design and Coding': 'Architecture_Coding_Design.md'

theme:
    name: readthedocs
