site_name: 2020_5BI_Team6

nav:
    - 'Project Charter 1': 'project_charter_client.md'
    - 'Project Charter 2': 'project_charter_server.md'
    - 'Software Requirements Specification': 'Software_Requirements_Specification.md'
    - 'Software Project Management Plan': 'Software_Project_Management_Plan.md'
   
    
theme:
    name: readthedocs

